repos:
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.9.3
  hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

- repo: https://github.com/psf/black
  rev: 21.8b0
  hooks:
  - id: black
    language_version: python3

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910
  hooks:
  - id: mypy
    additional_dependencies: [types-requests, types-PyYAML]