repos:
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.10.1
  hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

- repo: https://github.com/psf/black
  rev: 22.6.0
  hooks:
  - id: black
    language_version: python3

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.971
  hooks:
  - id: mypy
    additional_dependencies: [types-requests, types-PyYAML]